# Generated by Django 5.1.2 on 2024-11-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feastinsight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='enhanced_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='theme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
