# Generated by Django 5.1.2 on 2024-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feastinsight", "0002_place_enhanced_name_review_sentiment_review_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
