# Generated by Django 5.1.3 on 2024-11-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feastinsight", "0003_alter_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="openai_sentiment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
